# Generated by Django 2.2.9 on 2020-08-21 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
        ('posts', '0002_auto_20200820_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='room',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='rooms.Room'),
            preserve_default=False,
        ),
    ]
